name: Matrix

on: [pull_request]

jobs:
  node-version:
    
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
        node-version: [6, 8, 10]
        Incude: # We can also use Incude, whch adds extra configuration when running ubuntu-latest + node 10
          - os: ubuntu-latest
            node-version: 10
            IS-EXAMPLE: "true"
        exclude:  
          - os: ubuntu-latest #Steps will not run for ubuntu-latest | node version 6
            node-version: 6
          - os: macos-latest #Steps will not run for macos-latest | node version 8
            node-version: 8
    runs-on: ${{ matrix.os }} # Picks OS from the list of os
    steps:
      - name: Log node version
        run: node -v

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }} # Picks node version from the list of node

      - name: Log node version after changing
        run: node -v